try fix unit tests

diff --git a/.github/workflows/job_build_test.yml b/.github/workflows/job_build_test.yml
--- a/.github/workflows/job_build_test.yml
+++ b/.github/workflows/job_build_test.yml
@@ -48,8 +48,14 @@ jobs:
       # Optional: Run Unit Tests
       - name: Run Unit Tests
         run: |
-          $vstestPath = (Get-ChildItem "C:\Program Files (x86)\Microsoft Visual Studio\2022" -Recurse -Filter vstest.console.exe -ErrorAction SilentlyContinue | Select-Object -First 1).FullName
-          & $vstestPath "demoTool.Tests\bin\$env:Build_Configuration\demoTool.Tests.dll"
+          $vstestPath = Get-ChildItem "C:\Program Files\Microsoft Visual Studio\2022" -Recurse -Filter vstest.console.exe -ErrorAction SilentlyContinue | Select-Object -First 1
+          
+          if (-not $vstestPath) {
+            Write-Error "vstest.console.exe NOT found"
+            exit 1
+          }
+
+          & "$($vstestPath.FullName)" "demoTool.Tests\bin\$env:Build_Configuration\demoTool.Tests.dll"
 
       - name: Display Calculated Version
         run: |
