combine build and test in one job

diff --git a/.github/workflows/job_build.yml b/.github/workflows/job_build.yml
--- a/.github/workflows/job_build.yml
+++ b/.github/workflows/job_build.yml
@@ -11,7 +11,7 @@ on:
         type: string
 
 jobs:
-  build:
+  build-test:
     runs-on: windows-latest
 
     env:
@@ -48,3 +48,36 @@ jobs:
         run: |
           echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
           echo "Branch: ${{ steps.gitversion.outputs.branchName }}"
+
+      # Run UnitTests
+      - name: Run Unit Tests
+        run: |
+          $vstestPath = Get-ChildItem "C:\Program Files\Microsoft Visual Studio\2022" -Recurse -Filter vstest.console.exe -ErrorAction SilentlyContinue | Select-Object -First 1
+
+          if (-not $vstestPath) {
+            Write-Error "vstest.console.exe NOT found"
+            exit 1
+          }
+
+          & "$($vstestPath.FullName)" `
+            "demoTool.Tests\bin\$env:Build_Configuration\*.Tests.dll" `
+            /Logger:"trx;LogFileName=UnitTestResults.trx" `
+            /ResultsDirectory:"TestResults" `
+            /TestAdapterPath:. `
+            /Settings:coverlet.runsettings
+
+      # Upload UnitTest Result files as artifacts, so they can be fetched by the coverage workflow
+      - name: Upload UnitTest Results
+        uses: actions/upload-artifact@v4
+        with:
+          name: unittest-results
+          path: TestResults/*.trx
+
+      # Publish results
+      - name: Publish UnitTest Results
+        uses: dorny/test-reporter@v2
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: test-results          # Name of the check run which will be created
+          path: TestResults/*.trx     # Path to test results
+          reporter: dotnet-trx        # Format of test results
